apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account
        version: v2
    spec:
      containers:
      - name: account
#        image: hemantseth0210/account:0.1.3
        image: hemantseth0210/account:0.1.8
        ports:
        - containerPort: 4080
---
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
spec:
  selector:
    app: account
  ports:
  - name: http
    port: 4080
---
