apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demo-dstrule
spec:
  host: customer.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 10m
      maxEjectionPercent: 100    
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-vs
spec:
  hosts:
  - "*"
  gateways:
  - demo-gateway
  http:
  - route:
    - destination:
        host: customer.default.svc.cluster.local
        subset: v1
        port:
          number: 3080
      weight: 50
    - destination:
        host: customer.default.svc.cluster.local
        subset: v2
        port:
          number: 3080
      weight: 50