apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
        version: v1
    spec:
      containers:
      - name: customer
#        image: hemantseth0210/customer:0.0.9
        image: hemantseth0210/customer:0.1.7
        ports:
        - containerPort: 3080
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  selector:
    app: customer
  ports:
  - name: http
    port: 3080
---
